# -*- coding: utf-8 -*-
"""Copy of rf_grid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_llNQ6efaobbLXRNq38ZMLsab1KL9WTl
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import GridSearchCV

train = pd.read_csv("train_sample.csv")
test = pd.read_csv("test_sample.csv")

label_encoder = LabelEncoder()
train["Date"] = label_encoder.fit_transform(train["Date"])
train["Time"] = label_encoder.fit_transform(train["Time"])
train["State/UnionTerritory"] = label_encoder.fit_transform(train["State/UnionTerritory"])
#train["ConfirmedIndianNational"] = label_encoder.fit_transform(train["ConfirmedIndianNational"])
#train["ConfirmedForeignNational"] = label_encoder.fit_transform(train["ConfirmedForeignNational"])
train.info()
features=train.drop(["Deaths"],axis=1)
target=train["Deaths"]

test["Date"] = label_encoder.fit_transform(test["Date"])
test["Time"] = label_encoder.fit_transform(test["Time"])
test["State/UnionTerritory"] = label_encoder.fit_transform(test["State/UnionTerritory"])
#test["ConfirmedIndianNational"] = label_encoder.fit_transform(test["ConfirmedIndianNational"])
#test["ConfirmedForeignNational"] = label_encoder.fit_transform(test["ConfirmedForeignNational"])
test.info()

param_grid = {
    "n_estimators": [500,1000],
    "max_depth": [10,20],
    "min_samples_split": [2,5,10],
    "min_samples_leaf": [1,5]
}

model = GridSearchCV(RandomForestRegressor(random_state=42),
                           param_grid = param_grid,
                           cv=5,
                           scoring="neg_mean_squared_error"
                           )

model.fit(features, target)

pred = model.predict(test)
test["Deaths"]= pred
test.to_csv("pred_sample6.csv", index=False)